name: Deploy Vite App to GitHub Pages

on:
  # 当代码推送到 main 分支时触发部署
  push:
    branches: ["main"]
  # 允许在 GitHub 界面上手动触发工作流
  workflow_dispatch:

# 设置 GITHUB_TOKEN 的权限，以便能够部署到 GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# 并发控制，避免同时多个部署运行
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20" # 使用 Node.js 20 LTS
          cache: "pnpm" # 使用 pnpm 缓存

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Build with Vite
        run: pnpm run build

      - name: Setup Pages
        uses: actions/configure-pages@v3

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          # Vite 默认的构建输出目录是 "dist"
          path: "./dist"

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
